<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.nimbus</groupId>
        <artifactId>nimbus-framework</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>nimbus-log</artifactId>
    <description>操作日志组件: @OperLog 注解切面 + 事件解耦</description>

    <dependencies>
        <dependency>
            <groupId>com.nimbus</groupId>
            <artifactId>nimbus-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.nimbus</groupId>
            <artifactId>nimbus-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>